# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'EverestTours' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EverestTours
pod 'Firebase/Core'
pod 'FirebaseUI'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Facebook'
pod 'JTAppleCalendar', '~> 7.0'

  target 'EverestToursTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
